<!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
<Project>
	<PropertyGroup>
		<Author>Lars Gullestrup</Author>
		<RepositoryUrl>https://github.com/SimplyUnnamed/EVEEsi.Net</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/SimplyUnnamed/EVEEsi.Net</PackageProjectUrl>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
		<!-- <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath> -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	
	
</Project>